Merged all files into one

diff --git a/photomanager b/photomanager
--- a/photomanager
+++ b/photomanager
@@ -5,8 +5,363 @@
 # Licenced under the terms of the LGLP
 # Created on 2020 May 9
 
-source photomanager_settings.sh
-source photomanager_functions.sh
+################################### SETTINGS ##################################
+
+SEMVER_X="1"
+SEMVER_Y="1"
+SEMVER_Z="1"
+SEMVER_A=""
+# Folders
+OUT_FOLDER="."
+# Verbose ?
+DEBUG="no"
+VERBOSITY="s" # s(tdout) | l(og) | q(uiet)
+# log
+MAIN_LOG="photomanager.log"
+CLEAN="no"
+CHECK="no"
+
+# Regex
+REGEX_SEP="[A-Za-z -_]*"
+REGEX_YEAR="[0-9]{4}"
+REGEX_MONTH="[0-9]{2}"
+REGEX_DAY="[0-9]{2}"
+REGEX_DATE="($REGEX_YEAR)($REGEX_MONTH)($REGEX_DAY)"
+REGEX_TCODE="[0-9]{4,6}?"
+REGEX_NOTE="[A-Za-z -_]*"
+REGEX_EXT="\.[[:alnum:]]{3,4}"
+
+REGEX_DATE_FORM="[0-9]{4}-[0-9]{2}-[0-9]{2}"
+
+REGEX_FINAL="^($REGEX_SEP)$REGEX_DATE($REGEX_SEP)($REGEX_TCODE)($REGEX_NOTE)($REGEX_EXT)\$"
+# ^([A-Za-z -_]*)([0-9]{4})([0-9]{2})([0-9]{2})([A-Za-z -_]*)([0-9]{4,6}?)([A-Za-z -_]*)(\.[[:alnum:]]{3,4})$
+REGEX_TARGET="^$REGEX_DATE_FORM( [0-9]{4,6}(_[0-9]+)?)?$REGEX_EXT\$"
+REGEX_INTER="^$REGEX_DATE_FORM $REGEX_EXT\$"
+
+########## ARGUMENTS ###########
+ARGUMENT_STRING="slqo:fctdvh"
+TEST="no"
+TOUCHED=0
+MOVED=0
+
+###############################################################################
+
+
+
+################################## FUNCTIONS ##################################
+
+function version()
+{
+    SEMVER=$SEMVER_X.$SEMVER_Y
+    if [ -n "$SEMVER_Z" ]; then
+        SEMVER+=".$SEMVER_Z"
+    fi
+    if [ -n "$SEMVER_A" ]; then
+        SEMVER+="-$SEMVER_A"
+    fi
+    script=$(basename "$0")
+    echo "$script version $SEMVER"
+}
+
+function usage()
+{
+    echo "Use : $(basename "$0") [OPTIONS]... FOLDER"
+    echo "rename files in FOLDER accordingly to metadata or filename structure."
+    echo ""
+    echo "  -s          write to stdout (default)"
+    echo "  -l          write to log file ($MAIN_LOG)"
+    echo "  -q          quiet"
+    echo ""
+    echo "  -o [FOLDER] move renamed files into FOLDER"
+    echo "  -f          clean, moves file to corresponding year folder"
+    echo ""
+    echo "  -c          check if files are properly renamed" 
+    echo "  -t          do not rename, just pretend"
+    echo "  -d          show debug messages"
+    echo "  -h          show this message"
+    echo ""
+    echo "$(version)"
+    echo "Licenced under the terms of the LGLP"
+    echo ""
+}
+
+function debug()
+{
+    if [ "$DEBUG" = "yes" ]; then
+        echo "DEBUG : $1"
+    fi
+}
+
+function say()
+{
+    if [ "$VERBOSITY" = "s" ]; then
+        echo "$1"
+    elif [ "$VERBOSITY" = "l" ]; then
+        echo "$1" >> "$MAIN_LOG"
+    fi
+}
+
+function lowercaseName()
+{
+    echo "$1" | tr '[:upper:]' '[:lower:]'
+}
+
+function ensureFolderExists()
+{
+    if [ -z "$1" ]; then
+        say "Error : function ensureFolderExists must have one argument. Aborting"
+        return 255
+    else
+        if [ ! -d "$1" ]; then
+            say "Create folder $1"
+            mkdir "$1/"
+        fi
+    fi
+}
+
+function getFileName()
+{
+    if [ -z "$1" ]; then
+        return 255
+    else
+        filename=$(basename -- "$1")
+        echo "$filename"
+    fi
+}
+
+function getBaseName()
+{
+    if [ -z "$1" ]; then
+        return 255
+    else
+        basename=$(basename -- "$1" | cut -d'.' -f1)
+        echo "$basename"
+    fi
+}
+
+function getFileExtension()
+{
+    if [ -z "$1" ]; then
+        return 255
+    else
+        echo "$1" | sed 's/.*\.//g'
+    fi
+}
+
+function getDateTimeTag()
+{
+    TAG=$(file "$1" | grep datetime)
+    if [ -z "$TAG" ]; then
+        return 255
+    fi
+    echo "$TAG" | sed 's/^.*datetime=//' | cut -d',' -f1 | cut -d']' -f1
+}
+
+function makeNameFromTag()
+{
+    if [ $# -ne 1 ]; then
+        return 255
+    fi
+    TAG="$1"
+    YYYY=$(echo "$TAG" | cut -d':' -f1)
+    MM=$(echo "$TAG" | cut -d':' -f2)
+    DD=$(echo "$TAG" | cut -d':' -f3 | cut -f1 -d' ')
+    HH=$(echo "$TAG" | cut -d':' -f3 | cut -f2 -d' ')
+    mm=$(echo "$TAG" | cut -d':' -f4)
+    SS=$(echo "$TAG" | cut -d':' -f5)
+    newname="$YYYY-$MM-$DD $HH$mm$SS.$EXT"
+
+    echo "$newname"
+}
+
+function makeNameFromFile()
+{
+    if [ $# -ne 1 ]; then
+        return 255
+    fi
+    string="$1"
+    string=$(echo "$string" | sed -E -e "s/^$REGEX_FINAL\$/\2-\3-\4 \6\8/")
+    if [[ "$string" =~ $REGEX_INTER ]]; then # string malformed
+        string=$(echo "$string" | tr -d ' ')
+    fi
+    echo "$string"
+
+}
+
+function makeUniqueFilename()
+{
+    if [ $# -ne 1 ]; then
+        return 255
+    fi
+    tmp_name="$1"
+    if [ ! -f "$OUT_FOLDER/$tmp_name" ]; then
+        echo "$tmp_name"
+        return 0
+    else
+        IDX=1
+        baseName=$(echo "$tmp_name" | cut -d'.' -f1)
+        EXT=$(getFileExtension "$tmp_name")
+
+        comparison_name="$baseName"
+        comparison_name+="_"
+        comparison_name+="$IDX"
+        comparison_name+="."
+        comparison_name+="$EXT"
+
+        while [ -f "$OUT_FOLDER/$comparison_name" ]; do
+            IDX=$((IDX + 1))
+            comparison_name="$baseName"
+            comparison_name+="_"
+            comparison_name+="$IDX"
+            comparison_name+="."
+            comparison_name+="$EXT"
+        done
+
+        echo "$comparison_name"
+    fi
+}
+
+function RoutineRenameMeta()
+{
+    file="$1"
+    # extracting extension
+    EXT=$(getFileExtension "$file")
+    if [ $? -eq 255 ]; then
+        say "Error - function getFileExtension must have an argument. Aborting"
+        return 127
+    fi
+
+    # extracting TAG
+    TAG=$(getDateTimeTag "$file")
+    if [ $? -eq 255 ]; then
+        say "No datetime TAG found for $1, skipping"
+        return 127
+    fi
+
+    # building new name
+    newName=$(lowercaseName "$(makeNameFromTag "$TAG")")
+    if [ $? -eq 255 ]; then
+        say "Error - function makeNameFromTag and lowercaseName must have an argument. Aborting"
+        return 127
+    fi
+
+    # checking newName unicity, building an other new name if necessary
+    modName=$(makeUniqueFilename "$newName")
+    if [ $? -eq 255 ]; then
+        say "Error - function makeUniqueFilename must have an argument. Aborting"
+        return 127
+    fi
+
+    if [ "$TEST" = "yes" ]; then
+        say "moving $file to $OUT_FOLDER/$modName"
+        return 1
+    fi
+
+    # finally moving the file
+    if mv -n "$1" "$OUT_FOLDER/$modName"; then
+        say "moving $file to $OUT_FOLDER/$modName"
+        TOUCHED=$((TOUCHED + 1))
+    else
+        say "$file hasn't been renamed. Please investigate"
+        return 127
+    fi
+    return 0
+}
+
+function RoutineRenameFile()
+{
+    file="$1"
+    # is filename matching the regex?
+    if [[ "$file"  =~ $REGEX_FINAL ]]; then
+        # renaming with the regex
+        newName=$(makeNameFromFile "$file")
+    else
+        say "Error - can't rename $file. Filename structure doesn't match"
+        return 128
+    fi
+
+    # building new name
+    newName=$(lowercaseName "$newName")
+    if [ $? -eq 255 ]; then
+        say "Error - function newNameFromTag and lowercaseName must have an argument. Aborting"
+        return 127
+    fi
+
+    # checking newName unicity, building an other new name if necessary
+    modName=$(makeUniqueFilename "$newName")
+    if [ $? -eq 255 ]; then
+        say "Error - function makeUniqueFilename must have an argument. Aborting"
+        return 127
+    fi
+
+    if [ "$TEST" = "yes" ]; then
+        say "moving $file to $OUT_FOLDER/$modName"
+        return 1
+    fi
+
+    # finally moving the file
+    if mv -n "$1" "$OUT_FOLDER/$modName"; then
+        say "moving $file to $OUT_FOLDER/$modName"
+        TOUCHED=$((TOUCHED + 1))
+    else
+        say "$file hasn't been renamed. Please investigate"
+        return 127
+    fi
+}
+
+function checkProperRename()
+{
+    GOOD=0
+    BAD=0
+    for file in *; do
+        if [ -f "$file" ]; then
+            if [[ ! $file =~ $REGEX_TARGET ]]; then
+                echo "Filename $file not compliant with regexp."
+                BAD=$((BAD + 1))
+            else
+                echo "Filename $file is properly formed !"
+                GOOD=$((GOOD + 1))
+            fi
+        fi
+    done
+
+    echo "$GOOD file(s) with correct name"
+    echo "$BAD file(s) with incorrect name"
+}
+
+function moveToYearFolder()
+{
+    filename=$1
+    if [[ ! $filename =~ $REGEX_TARGET ]]; then
+        echo "Filename $filename not compliant with regexp. Aborting."
+        return 255
+    fi
+
+    YEAR=$(echo "$filename" | cut -c1-4)
+
+    # on vérifie l'existence du dossier de destination, sinon on le crée
+    if [ ! -d "$YEAR" ]; then
+        say "Creating $YEAR folder"
+        mkdir "$YEAR"
+    fi
+
+    # on vérifie qu'un fichier du même nom n'existe pas déjà
+    modName=$(makeUniqueFilename "$1")
+    if [ $? -eq 255 ]; then
+        return 127
+    fi
+
+    if mv -n "$filename" "$YEAR/$modName"; then
+        echo "moving $filename to $YEAR/$modName"
+        MOVED=$((MOVED + 1))
+    else
+        say "$filename hasn't been renamed. Please investigate"
+        return 125
+    fi
+}
+
+###############################################################################
+
 
 ############# Arg management ##############
 while getopts "$ARGUMENT_STRING" option; do
@@ -44,10 +399,12 @@ while getopts "$ARGUMENT_STRING" option; do
             exit 0
             ;;
         h )
-            usage            
+            usage
+            exit 0
             ;;
         *)
             usage
+            exit 255
             ;;
     esac
 done
@@ -82,10 +439,11 @@ for file in *; do
     fi
 done
 
+
 # Move the files into the appropriates folder if asked
 if [ $CLEAN = "yes" ]; then
     cd "$OUT_FOLDER" || exit
-    for file in ./*; do
+    for file in *; do
         if [ -f "$file" ]; then
             moveToYearFolder "$file"
         fi
